#!/bin/bash

# Определяем начальные значения переменных
input_file=""
output_file=""
operation=""

# Цикл, который рассматривает все возможные аргументы и сохраняет соответствующие значения в переменных
while getopts "i:o:d:" opt; do
  case ${opt} in
    i ) input_file="$OPTARG";;
    o ) output_file="$OPTARG";;
    d ) operation="$OPTARG";;
    \? ) echo "Недопустимый аргумент: $OPTARG"; exit 1;;
    : ) echo "Аргумент $OPTARG требует значения"; exit 1;;
  esac
done

# Функция для подсчета количества четных чисел
function count_even_numbers() {
  even_count=0
  while read num; do
    if [[ $num =~ [0-9]+ ]] && (( num % 2 == 0 )); then
      even_count=$((even_count + 1))
    fi
  done < "$input_file"
  echo "Количество четных чисел: $even_count" >> "$output_file"
}

# Функция для подсчета количества нечетных чисел
function count_odd_numbers() {
  odd_count=0
  while read num; do
    if [[ $num =~ [0-9]+ ]] && (( num % 2 == 1 )); then
      odd_count=$((odd_count + 1))
    fi
  done < "$input_file"
  echo "Количество нечетных чисел: $odd_count" >> "$output_file"
}

# Проверяем, существуют ли файлы входных данных и файла вывода
if [[ ! -f "$input_file" ]]; then
  echo "Файл входных данных не найден: $input_file"
  exit 1
fi

if [[ ! -f "$output_file" ]]; then
  echo "Файл вывода не найден, создаем файл: $output_file"
  touch "$output_file"
fi

# Проверяем третий аргумент и вызываем соответствующую функцию
case "$operation" in
  even ) count_even_numbers;;
  odd ) count_odd_numbers;;
  * ) echo "Неизвестная операция: $operation"; exit 1;;
esac

