name: Test script.sh

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Run script with even operation
      run: |
        chmod +x script.sh
        ./script.sh -i input.txt -o output.txt -d even

    - name: Check output for even operation
      run: |
         output=$(cat output.txt)
          if [[ $output == *"Количество четных чисел"* ]]; then
            echo "Even operation test passed"
          else
            echo "Even operation test failed"
            exit 1
          fi

    - name: Run script with odd operation
      run: |
        ./script.sh -i input.txt -o output.txt -d odd

    - name: Check output for odd operation
      run: |
         output=$(cat output.txt)
         if [[ $output == *"Количество нечетных чисел"* ]]; then
           echo "Odd operation test passed"
         else
           echo "Odd operation test failed"
           exit 1
         fi
